### PR TITLE
Mpmoine

### PR DESCRIPTION
**Pull request by mpmoine**
Require inialization from CMIP5 for another model configuration : CRNM-ESM2-1
Thanks!

### CODE REVIEW

**Comment by davidhassell** [comment]
Hi Marie-Pierre,

Was this model documented for CMIP5? Looking at the CMIP5 Models at http://search.es-doc.org, only shows CNRM-CM5 .... There may be more going on here, so please let me know if you think that this model was documeted back then. If it wasn't, then seeding will not be possible, I'm afraid.

Thanks, David

**Comment by mpmoine** [comment]
Hi David,

Correct! ESM configuration did not exist in CMIP5 for our model. But I thought it could be initialized with CNRM-CM5 (AOGCM configuration).

Anyway, if you confirm (*) that we can reuse the spreadsheets (apart the ocnbgchem's one) of CNRM-CM6-1 (CMIP6 AOGCM configuration), seeded with CNRM-CM5 (CMIP5 AOGCM configuration) for CNRM-ESM2-1 (CMIP6 ESM configuration) then my demand for initializing-from-CMIP5 is no longer necessary.

(*) I wrongly sent to the liaison list instead of the support one this morning:
```
Dear Es-Doc support,

Just a quick simple question (sorry to ask, but I don't know how to make a "diff" between 2 excels docs).

I guess that the only difference between ESM and AOGCM xls documents is the additional spreadsheet for "ocnbgchem" real. Could you please confirm the spreadsheets related to 8 other realms remain identicals between AOGCM and ESM?

This question is to know whether or not we can propagate the 8 common spreadsheets across the various model confgurations (AOGCM, ESM, LR, HR...).

Best regards,

Marie-Pierre.
```

Thanks,
Marie-Pierre.

**Comment by davidhassell** [comment]
Very sorry - my mistake! I misread your original message (reading "from" instead of "for"). Yes, you can do that initialization. For teh releveant CMIP6 model, just put entries like:

```
"atmos": {
            "initializedFrom": "cmip5:cnrm-cm5"
}, 
```
in your https://github.com/ES-DOC-INSTITUTIONAL/cnrm-cerfacs/blob/master/cmip6/models/initialization_from_CMIP5.json

When you've done this, let us know so we can do the injection.

Many thanks,
David

**Comment by mpmoine** [comment]
@davidhassell 

No big deal! Now I think we understood each other :-)

What you are suggesting (put "initializedFrom": "cmip5:cnrm-cm5") for the realms of cnrm-esm2-1  what I did with the current pull request, please see my [commit](https://github.com/ES-DOC-INSTITUTIONAL/cnrm-cerfacs/pull/3/commits/0e5912fa2432a1c81342b71c6ae2de58c9aff255)

Thanks,
Marie-Pierre.

**Comment by davidhassell** [comment]
OK - that looks fine, thanks. If you merge your pull request into master, we can implement the initialization ....

**Review by esgpub — APPROVED** [review]

**Comment by esgpub** [comment]
@davidhassell 

I have signed in with the "esgpub" login  (should be the admin one for this repository) but looks like esgpub has no merging permissions (I cannot see the `merge pull request` button). 

I think last time, Mark did it for us. But as "esgpub" user I should be able to merge, right?

Thanks,
Marie-Pierre.

**Pull request merged**
